default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: <%= ENV["PG_HOST"] %>

development:
  <<: *default
  database: john-hager-info_development
  reconnect: false
  # Set these in .bashrc or .bash_profile
  username: <%= ENV["PG_USER"] %> 
  password: <%= ENV["PG_PASS"] %>
  
test:
  <<: *default
  database: john-hager-info_test
  reconnect: false
  # Set these in .bashrc or .bash_profile
  username: <%= ENV["PG_USER"] %> 
  password: <%= ENV["PG_PASS"] %>
